trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipeline*.yml

parameters:
- name: StackAction
  displayName: StackAction
  type: string
  default: Deploy
  values:
  - 'Static Code Analysis'
  - 'Deploy'
  - 'Destroy'
- name: regionName
  displayName: regionName
  type: string
  default: 'us-east-1'

pool:
  vmImage: ubuntu-latest

variables:
  VpcStackName: 'VpcStack'
  SecurityGroupStackName: 'SgStack'
  AlbStackName: 'AlbStack'
  IamStackName: 'IamStack'
  S3BucketStackName: 'S3Stack'
  AsgStackName: 'AsgStack'
  S3BucketName: 'simpleawsarchitecture-artifacts'

  iac-templates-path: '$(System.DefaultWorkingDirectory)/cloudformation-templates'
  checkov-report-path: '$(System.DefaultWorkingDirectory)/checkov-report'
  checkov-report-format: 'junitxml'
  checkov-report-file: 'TEST-checkov-report.$(checkov-report-format)'

jobs:
  - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/static-analysis.yml'
    parameters:
      StackAction: ${{ parameters.StackAction }}
      iac-templates-path: ${{ variables.iac-templates-path }}
      checkov-report-path: ${{ variables.checkov-report-path }}
      checkov-report-format: ${{ variables.checkov-report-format }}
      checkov-report-file: ${{ variables.checkov-report-file }}

  # - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/deploy-resources.yml'
  #   parameters:

  # - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/destroy-resources.yml'
  #   parameters:
