trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipeline*.yml
    - azure-pipeline-templates/*
    - tools/*

parameters:
  - name: StackAction
    displayName: StackAction
    type: string
    default: Deploy
    values:
    - 'Deploy'
    - 'Destroy'
  - name: regionName
    displayName: regionName
    type: string
    default: 'us-east-1'

pool:
  vmImage: ubuntu-latest

variables:
  VpcStackName: 'VpcStack'
  SubnetStackName: 'SubnetStack'
  RouteTableStackName: 'RouteTableStack'
  SecurityGroupStackName: 'SgStack'
  AlbStackName: 'AlbStack'
  IamStackName: 'IamStack'
  S3BucketStackName: 'S3Stack'
  AsgStackName: 'AsgStack'
  CfnStackName: 'CfnStack'
  S3BucketName: 'simpleawsarchitecture-artifacts-20240214.6'

  iacTemplatesPath: '$(System.DefaultWorkingDirectory)/cloudformation-templates'
  checkovReportPath: '$(System.DefaultWorkingDirectory)/checkov-report'
  checkovReportFormat: 'csv'
  checkovReportFile: 'checkov-report.$(checkov-report-format)'

jobs:
- ${{ if eq(parameters.StackAction, 'Deploy') }}:
  - template: 'azure-pipeline-templates/static-analysis.yml'
    parameters:
      iacTemplatesPath: ${{ variables.iacTemplatesPath }}
      StackAction: ${{ parameters.StackAction }}
      checkovReportPath: ${{ variables.checkovReportPath }}
      checkovReportFormat: ${{ variables.checkovReportFormat }}
      checkovReportFile: ${{ variables.checkovReportFile }}

  - template: 'azure-pipeline-templates/manual-validation.yml'
    parameters:
      dependencyUsage: true
      dependencyExecution: CheckovScanner
      instructionMessage: 'Review the Static Code Analysis report and approve or reject the deployment.'

  - template: 'azure-pipeline-templates/deploy-resources.yml'
    parameters:
      iacTemplatesPath: ${{ variables.iacTemplatesPath }}
      StackAction: ${{ parameters.StackAction }}
      regionName: ${{ parameters.regionName }}
      S3BucketStackName: ${{ variables.S3BucketStackName }}
      VpcStackName: ${{ variables.VpcStackName }}
      SubnetStackName: ${{ variables.SubnetStackName }}
      RouteTableStackName: ${{ variables.RouteTableStackName }}
      SecurityGroupStackName: ${{ variables.SecurityGroupStackName }}
      AlbStackName: ${{ variables.AlbStackName }}
      IamStackName: ${{ variables.IamStackName }}
      AsgStackName: ${{ variables.AsgStackName }}
      CfnStackName: ${{ variables.CfnStackName }}
      S3BucketName: ${{ variables.S3BucketName }}

- ${{ if eq(parameters.StackAction, 'Destroy') }}:
  - template: 'azure-pipeline-templates/manual-validation.yml'
    parameters:
      instructionMessage: 'Do you want to destroy the current deployed resources?'

  - template: 'azure-pipeline-templates/destroy-resources.yml'
    parameters:
      StackAction: ${{ parameters.StackAction }}
      regionName: ${{ parameters.regionName }}
      S3BucketStackName: ${{ variables.S3BucketStackName }}
      VpcStackName: ${{ variables.VpcStackName }}
      SubnetStackName: ${{ variables.SubnetStackName }}
      RouteTableStackName: ${{ variables.RouteTableStackName }}
      SecurityGroupStackName: ${{ variables.SecurityGroupStackName }}
      AlbStackName: ${{ variables.AlbStackName }}
      IamStackName: ${{ variables.IamStackName }}
      AsgStackName: ${{ variables.AsgStackName }}
      CfnStackName: ${{ variables.CfnStackName }}
      S3BucketName: ${{ variables.S3BucketName }}
