trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - azure-pipeline*.yml

parameters:
- name: StackAction
  displayName: StackAction
  type: string
  default: Deploy
  values:
  - 'Static Code Analysis'
  - 'Deploy'
  - 'Destroy'
- name: regionName
  displayName: regionName
  type: string
  default: 'us-east-1'

pool:
  vmImage: ubuntu-latest

variables:
  VpcStackName: 'VpcStack'
  SecurityGroupStackName: 'SgStack'
  AlbStackName: 'AlbStack'
  IamStackName: 'IamStack'
  S3BucketStackName: 'S3Stack'
  AsgStackName: 'AsgStack'
  S3BucketName: 'simpleawsarchitecture-artifacts'

  iacTemplatesPath: '$(System.DefaultWorkingDirectory)/cloudformation-templates'
  checkovReportPath: '$(System.DefaultWorkingDirectory)/checkov-report'
  checkovReportFormat: 'junitxml'
  checkovReportFile: 'TEST-checkov-report.$(checkov-report-format)'

jobs:
  - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/static-analysis.yml'
    parameters:
      StackAction: ${{ parameters.StackAction }}
      iacTemplatesPath: ${{ variables.iacTemplatesPath }}
      checkovReportPath: ${{ variables.checkovReportPath }}
      checkovReportFormat: ${{ variables.checkovReportFormat }}
      checkovReportFile: ${{ variables.checkovReportFile }}

  # - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/deploy-resources.yml'
  #   parameters:

  # - template: '$(System.DefaultWorkingDirectory)/azure-pipeline-templates/destroy-resources.yml'
  #   parameters:
