AWSTemplateFormatVersion: 2010-09-09

Description: EC2 cloudformation template

Parameters:
  VpcStackName:
    Type: String
    Description: Name of the VPC stack
    MinLength: 1
    MaxLength: 255
    Default: VpcStack
  SecurityGroupStackName:
    Type: String
    Description: Name of the Security Group stack
    MinLength: 1
    MaxLength: 255
    Default: SgStack

Resources:
  SimpleNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      PrivateIpAddress: 10.0.1.19
      SourceDestCheck: true
      GroupSet:
        - Fn::ImportValue:
            !Sub ${SecurityGroupStackName}-SecurityGroup
      SubnetId:
        Fn::ImportValue:
          !Sub ${VpcStackName}-PublicSubnet1
      Tags:
        - Key: Name
          Value: SimpleNetworkInterface

  SimpleEbsVolume:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone: !GetAtt SimpleEc2Instance.AvailabilityZone
      Encrypted: true
      Size: 100
      Iops: 3000
      VolumeType: gp3
      Tags:
        - Key: Name
          Value: SimpleEbsVolume

  SimpleEbsVolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref SimpleEc2Instance
      VolumeId: !Ref SimpleEbsVolume

  SimpleEc2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b898040803850657
      InstanceType: t2.micro
      Monitoring: false
      NetworkInterfaces:
        - DeviceIndex: 0
          NetworkInterfaceId: !Ref SimpleNetworkInterface
      UserData:
        Fn::Base64: |
          #!/bin/bash
          sudo yum update -y
          sudo amazon-linux-extras install nginx1 -y
          sudo systemctl enable nginx
          sudo systemctl start nginx
      Tags:
        - Key: Name
          Value: SimpleEc2Instance
