parameters:
  - name: regionName
    type: string
  - name: S3BucketStackName
    type: string
  - name: VpcStackName
    type: string
  - name: SubnetStackName
    type: string
  - name: RouteTableStackName
    type: string
  - name: SecurityGroupStackName
    type: string
  - name: AlbStackName
    type: string
  - name: IamStackName
    type: string
  - name: AsgStackName
    type: string
  - name: CfnStackName
    type: string
  - name: S3BucketName
    type: string

jobs:
  - job: Destroy
    displayName: Destroy Simple architecture VPC, SGs, ALB and ASG
    dependsOn: ManualValidation
    condition: succeeded()
    steps:
      - task: CloudFormationDeleteStack@1
        name: DestroyCfnStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(CfnStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroyASGStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(AsgStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroyALBStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(AlbStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroySecurityGroupStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(SecurityGroupStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroyIAMStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(IamStackName)

      - task: AWSShellScript@1
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          arguments: '$(S3BucketName)'
          scriptType: 'filePath'
          filePath: '$(Build.Repository.LocalPath)/tools/empty_s3bucket.sh'

      - task: CloudFormationDeleteStack@1
        name: DestroyS3BucketStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(S3BucketStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroyRouteTableStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(RouteTableStackName)

      - task: CloudFormationDeleteStack@1
        name: DestroySubnetStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(SubnetStackName)
      
      - task: CloudFormationDeleteStack@1
        name: DestroyVpCStack
        inputs:
          awsCredentials: 'Iac'
          regionName: '${{ parameters.regionName }}'
          stackName: $(VpcStackName)
