parameters:
- name: StackAction
  type: string
- name: iacTemplatesPath
  type: string
- name: checkovReportPath
  type: string
- name: checkovReportFormat
  type: string
- name: checkovReportFile
  type: string

jobs:
  - job: CheckovScanner
    displayName: IAC scanner using Checkov
    condition: ${{ eq(parameters.StackAction, 'Static Code Analysis') }}
    steps:
      - task: Bash@3
        displayName: 'install Checkov'
        inputs:
          targetType: 'inline'
          script: 'pip3 install checkov'

      - task: Bash@3
        displayName: 'Checkov Static Code Analysis'
        inputs:
          targetType: 'inline'
          script: |
            mkdir $(checkovReportPath)
            checkov -d $(iacTemplatesPath) \
              --framework cloudformation \
              --output $(checkovReportFormat) \
              --output-file-path '$(checkovReportPath)/$(checkovReportFile)' \
              --soft-fail

      - task: PublishBuildArtifacts@1
        displayName: 'Export Checkov Static Code Analysis'
        inputs:
          PathtoPublish: '$(checkovReportPath)/$(checkovReportFile)'
          ArtifactName: 'checkov-report'
          publishLocation: 'Container'
