AWSTemplateFormatVersion: 2010-09-09

Description: CF cloudformation template

Parameters:
  AlbStackName:
    Type: String
    Description: Name of the ALB stack
    MinLength: 1
    MaxLength: 255

Resources:
  # SimpleCFCachePolicy:
  #   Type: 'AWS::CloudFront::CachePolicy'
  #   Properties:
  #     CachePolicyConfig:
  #       Name: SimpleCFCachePolicy
  #       DefaultTTL: 0
  #       MaxTTL: 0
  #       MinTTL: 0
  #       ParametersInCacheKeyAndForwardedToOrigin:
  #         CookiesConfig:
  #           CookieBehavior: all
  #         EnableAcceptEncodingBrotli: false
  #         EnableAcceptEncodingGzip: false
  #         HeadersConfig:
  #           HeaderBehavior: none
  #         QueryStringsConfig:
  #           QueryStringBehavior: all

  SimpleCFDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - Id: SimpleAlbOrigin
          DomainName: 
            Fn::ImportValue: !Sub ${AlbStackName}-DnsName
          CustomOriginConfig:
            HTTPPort: '80'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.php
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: SimpleAlbOrigin
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
