AWSTemplateFormatVersion: "2010-09-09"
Description: IAM cloudformation template

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket
    MinLength: 1
    MaxLength: 255

Resources:
  InstanceRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      Path: /
      Policies:
        - PolicyName: devops
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - "s3:Get*"
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - ${S3BucketName}
                      - '/*'
              - Effect: Allow
                Action:
                  - "s3:List*"
                Resource:
                  - !Join
                    - ''
                    - - 'arn:aws:s3:::'
                      - ${S3BucketName}

  EC2InstanceProfile:
    Type: 'AWS::IAM::InstanceProfile'
    Properties:
      Path: /
      Roles:
        - !Ref InstanceRole

Outputs:
  EC2InstanceProfile:
    Description: EC2 Instance Profile
    Value: !Ref EC2InstanceProfile
    Export:
      Name: !Sub ${AWS::StackName}-EC2InstanceProfile
