AWSTemplateFormatVersion: 2010-09-09

Description: VPC cloudformation template

Resources:
  SimpleVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsHostnames: false
      EnableDnsSupport: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value: SimpleVPC

  SimpleInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: SimpleInternetGateway

  SimpleAttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref SimpleVPC
      InternetGatewayId: !Ref SimpleInternetGateway

  SimpleElasticIP1:
   Type: AWS::EC2::EIP
   Properties:
      Domain: vpc
  
  SimpleElasticIP2:
   Type: AWS::EC2::EIP
   Properties:
      Domain: vpc

Outputs:
  VPC:
    Description: A reference to the created VPC
    Value: !Ref SimpleVPC
    Export:
      Name: !Sub ${AWS::StackName}-VPC
  InternetGateway:
    Description: A reference to the created InternetGateway
    Value: !Ref SimpleInternetGateway
    Export:
      Name: !Sub ${AWS::StackName}-InternetGateway
  ElasticIP1:
    Description: A reference to the created ElasticIP1
    Value: !GetAtt SimpleElasticIP1.AllocationId
    Export:
      Name: !Sub ${AWS::StackName}-ElasticIP1
  ElasticIP2:
    Description: A reference to the created ElasticIP2
    Value: !GetAtt SimpleElasticIP2.AllocationId
    Export:
      Name: !Sub ${AWS::StackName}-ElasticIP2
