AWSTemplateFormatVersion: 2010-09-09

Description: CF cloudformation template

Parameters:
  AlbStackName:
    Type: String
    Description: Name of the ALB stack
    MinLength: 1
    MaxLength: 255

Resources:
  SimpleCFDistribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Origins:
        - Id: SimpleAlbOrigin
          DomainName: 
            Fn::ImportValue: !Sub ${AlbStackName}-DnsName
          CustomOriginConfig:
            HTTPPort: '80'
            OriginProtocolPolicy: http-only
        Enabled: 'true'
        DefaultRootObject: index.php
        DefaultCacheBehavior:
          AllowedMethods:
          - DELETE
          - GET
          - HEAD
          - OPTIONS
          - PATCH
          - POST
          - PUT
          TargetOriginId: SimpleAlbOrigin
          ViewerProtocolPolicy: allow-all
        PriceClass: PriceClass_100
